### PR TITLE
Add "Minimal Notion Icons" set

### PR DESCRIPTION
**Pull request by fabiosangregorio**
This PR adds two "Minimal Notion Icons" sets of 200+ icons by an unknown author ([link to the source here](https://www.notion.so/Minimal-Notion-Icons-a6735b20d07a4ed5a04ef2538170f423)):
* Colored
* Monochromatic

These sets are licensed under the Creative Commons License (as stated in the page).

Please note that the sets path in `icons.json` is currently pointing to my fork. Let me know if I should remove the corresponding lines.

### CODE REVIEW

**Comment by dragonwocky** [comment]
Nice - please add the Creative Commons license into the folders with the images before merge.

**Comment by fabiosangregorio** [comment]
Of course, I'll do this this morning.
As in the first comment, the sets path in icons.json is currently pointing to my fork. Please let me know if I should remove the corresponding lines.

**Comment by dragonwocky** [comment]
Ah, missed that before. Yeah, it's better if things are served from the main repo rather than a fork.

**Comment by fabiosangregorio** [comment]
I added the license files and removed the `sourceUrl`s from `icons.json`. This PR should be ready to be merged now.

**Pull request merged**
